# Generated by Django 5.2 on 2025-04-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='title',
            new_name='name',
        ),
    ]
